apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k3s
  name: k3s
spec:
  containers:
  - command:
    - k3s
    - server
    - --agent-token
    - aaa
    - --disable-agent
    - --config
    - /output/kubeconfig.yaml
    - --write-kubeconfig-mode
    - "666"
    name: server
    image: k3s:server
    ports:
    - containerPort: 6443
      hostPort: 6443
      protocol: TCP
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/rancher/k3s
      name: k3s-volume
    - mountPath: /output
      name: k3s-host
  - command:
      - sleep
      - "10000"
    # - k3s
    # - agent
    # - --token
    # - aaa
    # - --server
    # - https://k3s-server:6443
    name: worker
    image: k3s:worker
    ports:
    - containerPort: 6442
      hostPort: 6442
      protocol: TCP
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      privileged: true
    #   allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: /run
      name: tempfs
      subPath: run
    - mountPath: /var/run
      name: tempfs
      subPath: var-run
  restartPolicy: Never
  volumes:
    - name: k3s-volume
      PersistentVolumeClaim:
        claimName: k3s-volume-claim
    - name: k3s-host
      hostPath:
        path: /Users/josephdipilato/Documents/thing/repos/project-template/containers/cluster
        type: Directory
    - name: tempfs
      emptyDir:
        medium: Memory
        sizeLimit: 64Mi
