apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gitlab
  name: gitlab
spec:
  containers:
  - name: gitlab
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.example.com
    ports:
    - containerPort: 22
      hostPort: 2201
      protocol: TCP
    - containerPort: 80
      hostPort: 8081
      protocol: TCP
    - containerPort: 443
      hostPort: 4401
      protocol: TCP
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      privileged: false
    volumeMounts:
    - name: gitlab-config
      mountPath: /etc/gitlab
      subPath: config
    - name: gitlab-data
      mountPath: /var/log/gitlab
      subPath: logs
    - name: gitlab-data
      mountPath: /var/opt/gitlab
      subPath: data
  restartPolicy: Never
  volumes:
    - name: gitlab-config
      PersistentVolumeClaim:
        claimName: gitlab-config-pvc
    - name: gitlab-data
      PersistentVolumeClaim:
        claimName: gitlab-data-pvc
