apiVersion: v1
kind: Pod
metadata:
  labels:
    app: registry
  name: registry
spec:
  containers:
  - name: registry
    image: registry:latest
    ports:
    - containerPort: 5000
      hostPort: 5000
      protocol: TCP
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      privileged: false
    volumeMounts:
    - name: registry-data
      mountPath: /var/lib/registry
      subPath: registry
  restartPolicy: Never
  volumes:
    - name: registry-data
      PersistentVolumeClaim:
        claimName: registry-data-pvc