###############################################################################
# ABOUT
###############################################################################
# This file will be included id all child pipelines

###############################################################################
# INCLUDES
###############################################################################
include:
  - local: config/gitlab/common/vars.yml
  - local: config/gitlab/common/types.yml
  - local: config/gitlab/common/includes.yml