###############################################################################
# VARIABLES
###############################################################################
variables:
  TAG:
    value: "develop"
    description: "Specify the tag name to use"
  PUSH:
    value: "false"
    description: "Push - Valid Options: [true,false]"
  BUILD:
    value: "true"
    description: "BUILD - Valid Options: [true,false]"
  IMAGES:
    value: "false"
    description: "Push images - Valid Options: [true,false]"
  IMAGE_A:
    value: "false"
  IMAGE_B:
    value: "false"
  HELP_TEXT:
    value: "See Options below"
    description: >
      Options:
      IMAGE_A,
      IMAGE_B
