
FROM rockylinux:9 as os_layer
FROM os_layer as tools_layer

RUN dnf -y install cmake g++
RUN dnf -y install dnf-plugins-core
RUN dnf config-manager --set-enabled crb
RUN dnf -y install ninja-build

# WORKDIR /workspace/src
# COPY CMakeLists.txt .

FROM leetcode_base as fast_tools_layer

FROM fast_tools_layer as src_layer
WORKDIR /src
VOLUME [ "/src" ]

# COPY *.mine.cpp .

FROM src_layer as build_layer
VOLUME [ "/build" ]
# RUN cmake -B /build -S /src && cmake --build /build

VOLUME [ "/pwd" ]
# FROM build_layer as dependency_layer

# WORKDIR /build
# # RUN mkdir /deps
# RUN { ldd -r leet_code; ldd -r -u leet_code; } | sed -n '\,/, s|^[^/]*\([^ ]*\).*|\1|p' | sort | uniq -c | sed -n -e '/^ *1/ s| *1 \(.*\)|cp \1 /deps|p' | sh

# FROM rockylinux:9 as minimal
# COPY --from=dependency_layer /build /
# COPY --from=dependency_layer /deps /
ENTRYPOINT []
# CMD ["/build/leet_code"]
CMD /pwd/test_forever.sh