FROM alpine as os

###############################################################################
FROM os as config
RUN echo "check_certificate = off" >> ~/.wgetrc
RUN echo "--insecure" >> ~/.curlrc
RUN sed -i 's/https/http/g' /etc/apk/repositories
RUN apk add wget

###############################################################################
FROM config as k3s
WORKDIR /download
RUN wget https://github.com/k3s-io/k3s/releases/download/v1.25.3%2Bk3s1/k3s -O k3s
RUN wget https://github.com/k3s-io/k3s/releases/download/v1.25.3%2Bk3s1/k3s-airgap-images-amd64.tar.gz -O k3s-airgap-images-amd64.tar.gz 
RUN wget https://get.k3s.io. -O install.sh
RUN echo -e \
"mkdir -p /var/lib/rancher/k3s/agent/images/                               \n"\
"cp ./k3s-airgap-images-*.tar.gz /var/lib/rancher/k3s/agent/images/        \n"\
"cp ./k3s /usr/local/bin/k3s                                               \n"\
"chmod +x /usr/local/bin/k3s                                               \n"\
> setup.sh && chmod +x setup.sh

###############################################################################
FROM scratch as final
COPY --from=k3s /download/* /download/k3s/

# TODO vscodium
# TODO podman