# Common
###############################################################################
include:
  - local: "config/gitlab/common/common.yml"

# Jobs
###############################################################################
deploy:
  extends:
    - .deploy
  # services:
  #   - !reference [.deploy-common, services]
  before_script:
    - !reference [.deploy-common, before_script]
    - echo "Not Implemented"
  script:
    - !reference [.deploy-common, script]
    - echo "Not Implemented"
  after_script:
    - echo "Not Implemented"
    - !reference [.deploy-common, after_script]
  cache:
    - !reference [.deploy-common, cache]
  needs:
    - !reference [.deploy-common, needs]
  rules:
    - !reference [.deploy-common, rules]