# Common
###############################################################################
include:
  - local: "config/gitlab/common/common.yml"

# Jobs
###############################################################################
archive:
  extends:
    - .archive
  # services:
  #   - !reference [.archive-common, services]
  before_script:
    - !reference [.archive-common, before_script]
    - echo "Not Implemented"
  script:
    - !reference [.archive-common, script]
    - echo "Not Implemented"
  after_script:
    - echo "Not Implemented"
    - !reference [.archive-common, after_script]
  cache:
    - !reference [.archive-common, cache]
  needs:
    - !reference [.archive-common, needs]
  rules:
    - !reference [.archive-common, rules]