# Common
###############################################################################
include:
  - local: "config/gitlab/common/common.yml"

# Jobs
###############################################################################
project-docs:
  extends:
    - .project-docs
  # services:
  #   - !reference [.project-docs-common, services]
  before_script:
    - !reference [.project-docs-common, before_script]
    - echo "Not Implemented"
  script:
    - !reference [.project-docs-common, script]
    - echo "Not Implemented"
  after_script:
    - echo "Not Implemented"
    - !reference [.project-docs-common, after_script]
  cache:
    - !reference [.project-docs-common, cache]
  needs:
    - !reference [.project-docs-common, needs]
  rules:
    - !reference [.project-docs-common, rules]