###############################################################################
# INCLUDE
###############################################################################
include:
  - local: "config/gitlab/common/common.yml"
  - local: "config/gitlab/stages/all.yml"
